baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "coba-disqus"

[outputs]
home = ["HTML","RSS","Algolia"]

[outputFormats.Algolia]
  mediaType = "application/json"
  baseName = "algolia"
  isPlainText = true
  notAlternative = true
