baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "coba-disqus"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = ["HTML","RSS","Algolia"]

[outputFormats.Algolia]
  mediaType = "application/json"
  baseName = "algolia"
  isPlainText = true
  notAlternative = true
