[build]
functions = "./lambda"

[[redirects]]
from = "/businessinitiative/*"
to = "/businessinitiative/:splat"
status = 200
force = true
conditions = {Role = ["bi"]}
[[redirects]]
from = "/businessinitiative/*"
to = "/gated/"
status = 404
force = true