[build]
functions = "./lambda"

[[redirects]]
from = "/businessinitiativea/*"
to = "/businessinitiativea/:splat"
status = 200
force = true
conditions = {Role = ["superuser"]}

[[redirects]]
from = "/businessinitiativea/*"
to = "/gated/"
status = 401
force = true