[build]
functions = "./lambda"

[[redirects]]
from = "/businessinitiative/*"
to = "/businessinitiative/*"
status = 200
force = true
conditions = {Role = "bi"}

[[redirects]]
from = "/businessinitiative/*"
to = "/gated/"
status = 401
force = true