= Chital
:keywords: sti, sepulsa, whitelabel-order-system 

== Overview

Chital (/ tʃiːtəl / [2]) atau cheetal (sumbu Axis), juga dikenal sebagai rusa tutul atau rusa sumbu.
Merupakan spesies rusa yang asli di anak benua India.
Spesies ini pertama kali dijelaskan oleh naturalis Jerman Johann Christian Polycarp Erxleben pada 1777.

Rusa berukuran sedang, chital jantan mencapai hampir 90 cm (35 in) dan betina 70 cm (28 in) di bahu.
Sementara yang jantan memiliki berat 30--75 kg (66--165 pon), sedangkan yang betina  lebih ringan memiliki berat 25--45 kg (55--99 pon).
Spesies ini dimorfik secara seksual;
jantan lebih besar dari betina, dan tanduk hanya ada pada jantan.
Bagian atas berwarna emas hingga rufous, sepenuhnya tertutup bintik putih.
Perut, pantat, tenggorokan, bagian dalam kaki, telinga, dan ekor semuanya berwarna putih.
Panjang tanduknya, tiga cabang, panjangnya hampir 1 m (3,3 kaki).

Sepulsa.com _Backend_ untuk B2C dan API _endpoint_.

== Team Involved

|===
| *Name* | *Role* | *Email* 


| Ramdhan Pohan
| Product Owner
| rpohan@alterra.id


| Antonius Ananto
| Development Manager
| anton@alterra.id


| Hendrik Rahardja
| Lead Software Engineer
| hendrik@alterra.id


| Ferdinandus Eka
| Lead Quality Engineer
| ferdi@alterra.id


| Pipit Puspitasari
| Ex-Lead System Analyst
| pipit@alterra.id
|===

== Technical Information

<<docs/url-chital#, System URL Chital>>

<<docs/architecture-chital#, Architecture Chital>>

<<docs/technology-chital#, Technology Chital>>

<<docs/environment-chital#, Environment Chital>>

<<docs/flow-wire-chital#, Flow and Wireframe Chital>>

== Onboarding Information

<<docs/dev-onboarding-chital#, Developer Onboarding Chital>>

<<docs/development-chital#, Development Chital>>

== Documentation

<<docs/api-doc-chital#, API Documentation Chital>>

<<docs/adr-doc-chital#, ADR Document Chital>>

<<docs/product-information-chital#, Product Information Document Chital>>

<<docs/release-note-chital#, Release Notes Chital>>

<<docs/pivotal-chital#, Pivotal Project Chital>>

<<docs/feature-knowledge-chital#, Feature Knowledge Chital>>
