= Seingat Alicanto URL SEO Friendly

== Development Team

|===
| *Name* | *Role* | *Email* 

| R Achmad Syatriadi Widisana 
| Document Owner 
| widisana@alterra.id

| Hendrik Rahardja
| Development Manager 
| hendrik@alterra.id

| Ramdhan Pohan  
| Product Owner 
| rpohan@alterra.id

a|  1. R Achmad Syatriadi Widisana  
    2. Pipit Puspitasari 
 |  System analyst 
a|  1. widisana@alterra.id  
    2. pipit@alterra.id

| Ery Hardinata 
| Software Engineer 
| ery@alterra.id

| Mugh dzin syah 
| Front End Developer |
 dzinsyah@alterra.id

| Farras Herdicho 
| Quality Enggineer
 | farras@alterra.id
|===

== Overview

Sebuah fitur untuk menampilkan halaman transaksi berdasarkan kategori produk yang bersangkutan dengan url yang spesifik. Misalkan halaman transaksi untuk produk OVO, maka url untuk mengakses halaman transaksi OVO-nya menjadi www.sepulsa.com/transaction/uang-elektronik/ovo

=== Sistem Flow
* TODO

=== User Story
Berikut merupakan cara user untuk masuk ke halaman transaksi (contoh transaksi uang elektronik OVO):

. _User_ membuka web *www.sepulsa.com*.

. _User_ klik pilih _product_ lainnya, dan masuk ke halaman *www.sepulsa.com/menu*.

. _User_ klik pilih uang elektronik, dan pilih product OVO.

. Bisa dicek pada _address bar_, url-nya menjadi *www.sepulsa.com/transaction/uang-elektronik/ovo*.

. Selain lewat menu, _user_ juga bisa langsung mengakses halaman transaksi _product_ OVO dengan cara memasukkan url ini *www.sepulsa.com/transaction/uang-elektronik/ovo* ke _address bar_.

. _User_ memasukkan nomor dan memilih _product_ yang diinginkan, kemudian melakukan proses pembayaran seperti biasa.


=== Implementation

==== Proses Implementasi
* Membuat _pages_ baru di dalam folder _product_ yang bersangkutan dengan nama *_file [slug].js_*, misal _product_ uang elektronik, berarti buat pages [slug].js nya di directory pages/transaction/uang-elektronik/[slug].js

* Tambahkan parameter pada _link icon product categories_ yang bersangkutan. Misal pada _icon_ OVO, link-nya menjadi /uang-elektronik/ovo.

* Pada halaman [slug].js, ambil parameter _slug_ dengan cara _Router.query.slug_ kemudian integrasikan parameter tersebut dengan API yang disediakan oleh Chital.



