= Alicanto
:keywords: sti, sepulsa, whitelabel-order-system-client, chital

== Overview

Alicanto merupakan _frontend_ terbaru dari http://sepulsa.com[sepulsa.com] (_web apps_) yang menangani bisnis transaksi di  Sepulsa.
Alicanto terkoneksi dengan API dari Chital untuk memproses semua transaksi.
Hal itu menyebabkan sistem ini memiliki sebuah laporan _log_ dan bisa di-_maintenance_ di dalam sistem Chital.
Tidak hanya untuk transaksi, tetapi juga untuk mengelola _User_.

Alicanto atau Allicanto adalah burung mitologis gurun Atacama yang berkaitan dengan mitologi negara Chili.

== Team Involved

|===
| *Name* | *Role* | *Email* 

| Ramdhan Pohan
| Product Owner
| rpohan@alterra.id

| Antonius Ananto
| Development Manager
| anton@alterra.id

| Miftah Muhammad
| Software Engineer
| miftah@alterra.id

| Ferdinandus Eka
| Lead Quality Engineer
| ferdi@alterra.id

|===

== Technical Information

<<docs/url-alicanto.adoc#, System URL Alicanto>>

<<docs/architecture-alicanto.adoc#, Architecture Alicanto>>


<<docs/technology-alicanto.adoc#, Technology Alicanto>>

<<docs/environment-alicanto.adoc#, Environment Alicanto>>

<<docs/flow-wire-alicanto.adoc#, Flow and Wire Alicanto>>

== Onboarding Information

<<docs/development-alicanto.adoc#, Development Alicanto>>

<<docs/dev-onboarding-alicanto.adoc#, Developer Onboarding Alicanto>>

== Documentation

<<docs/adr-doc-alicanto.adoc#, ADR Document Alicanto>>

<<docs/product-information-alicanto.adoc#, Product Information Document Alicanto>>

<<docs/feature-knowledge-alicanto.adoc#, Feature Knowledge Alicanto>>
