= Release and Deployment Odoo

== Release Procedure

*_Release Preparation_:*

Berikut ini adalah persiapan rilis untuk Hermes dan ERP:

. Buat _release story_ di Pivotal
. Buat dengan nama _branch_ " `release/YYYYMMDD` " dari master _branch_.
. Merge semua _story_ diterima untuk _branch_ " `release/YYYYMMDD` ".
Jika terjadi konflik:
 .. Bandingkan jalur yang menyebabkan konflik dengan yang ada di DEV _environtment_, atau
 .. Minta developer untuk menyelesaikan konflik.
. Klik " `Finish` " di _story_.
. Lakukan test pada _branch_ " `release/YYYYMMDD` " di lokal _environment_ untuk  memastikan bahwa itu berfungsi sebagaimana dimaksud.
. _Merge_ branch  " `release/YYYYMMDD` " ke branch " `qa_branch-master` ".
Berikan informasi ke tim QE untuk update 33/5000 dan lakukan tes regresi skrip pada branch " `qa_branch-master` ".

== Deployment

=== Deployment Schedule

Saat ini, tidak ada jadwal yang ditetapkan untuk penempatan.
Itu dilakukan berdasarkan kebutuhan.

=== Deployment Process

. SSH ke server.
. Pull dan perbarui kode ke server
. Periksa URL sistem dan pastikan itu berfungsi dengan baik.

=== Rollback Step

. Buka tautan GitHub yang dinyatakan di bagian Kode Sumber.
. Lihat ID komit sebelumnya.
. Jalankan perintah berikut di server produksi:

         ----
         sudo service <service_name> restart                   
         sudo service nginx restart
         ----

. Periksa URL sistem dan pastikan semua fungsi berfungsi sebagaimana dimaksud.
